sudo: true
language: c

compiler:
  - gcc

os:
  - linux

sudo: required

before_install:
  - ./travis-install.sh

script:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./travis-build.sh; fi

addons:
  apt:
    sources:
      - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
      - meson
      - mosquitto

