sudo: true
language: c
dist: bionic

os:
  - linux

sudo: required

git:
  submodules: false
  depth: 10

before_install:
  - ./travis-install.sh
  - unset CC

script:
  - if [[ "$COVERITY_SCAN_BRANCH" != 1 ]]; then ./travis-build.sh; fi

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ninja-build
      - mosquitto

cache: ccache